version: '3.8'

services:
  weather-app:
    build:
      context: .
      args:
        NEXT_PUBLIC_GOOGLE_CLIENT_ID: ${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
    ports:
      - "80:80"
    environment:
      - VISUAL_CROSSING_API_KEY=${VISUAL_CROSSING_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - MODEL=gemini-2.5-flash
      - DISABLE_WEB_DRIVER=0
      - ENVIRONMENT=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3 