version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: weatherdb
      POSTGRES_USER: popard
      POSTGRES_PASSWORD: malySlon1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U popard -d weatherdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Weather Center Chat Application
  weather-app:
    build: .
    ports:
      - "80:80"
    environment:
      - DATABASE_URL=postgresql+psycopg2://popard:malySlon1@postgres:5432/weatherdb
      - VISUAL_CROSSING_API_KEY=${VISUAL_CROSSING_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - NEXT_PUBLIC_GOOGLE_CLIENT_ID=${NEXT_PUBLIC_GOOGLE_CLIENT_ID}
      - MODEL=gemini-2.0-flash
      - DISABLE_WEB_DRIVER=0
      - ENVIRONMENT=production
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data: 